
@base_url = http://localhost:5012

### Send chat endpoint

GET {{base_url}}/chat-raw?message=Open email and summarize top 10 emails I received today

### Find hacker news articles
GET {{base_url}}/chat-raw?message=Summarize top 10 hacker news articles

### Find hacker news articles
GET {{base_url}}/chat-raw?message=open chrome and search for tsla stock price


### Find hacker news articles
GET {{base_url}}/chat-raw?message=Summarize top 10 hacker news articles


### Find hacker news articles
GET {{base_url}}/chat-raw?message=open stack overflow search about the text I have selected

