
@base_url = http://localhost:5012

### Send chat endpoint

GET {{base_url}}/chat-raw?message=Open email and summarize top 10 emails I received today

### Find hacker news articles
GET {{base_url}}/chat-raw?message=Summarize top 10 hacker news articles

### Find hacker news articles
GET {{base_url}}/chat-raw?message=open chrome and search for tsla stock price

### Find hacker news articles
GET {{base_url}}/chat-raw?message=Summarize top 10 hacker news articles

### Send email
GET {{base_url}}/chat-raw?message=Use Apple Script and don't use computer API or module, Open email app and draft an email to John Doe with subject "Meeting tomorrow" and body "Hi John, I would like to meet you tomorrow at 10am. Please let me know if this time works for you. Thanks, Jane"

### Summarize top email
GET {{base_url}}/chat-raw?message=Use Apple Script and don't use computer API or module, Summarize top most email in my inbox

### Summarize top email
GET {{base_url}}/chat-raw?message=Use Apple Script and don't use computer API or module, Summarize top most email in my inbox

### Find hacker news articles
GET {{base_url}}/chat-raw?message=open stack overflow search about the text I have selected


### Research on TSLA stock
GET {{base_url}}/chat-raw?message=Do research about TSLA stocks and why did TSLA price jumped after earning even though it was a miss

### Research on TSLA stock
GET {{base_url}}/chat-raw?message=Do research about TSLA stocks and why did TSLA price jumped after earning even though it was a miss


### Research on TSLA stock
GET {{base_url}}/chat-raw?message=Show me top 10 producthunt app related to AI today. you could use https://www.producthunt.com/search?q=tes endpoint and take a picture then save it to my desktop

### Research on TSLA stock
GET {{base_url}}/chat-raw?message=Summarize the current repo, I am opening through VScode right now.